export {default as AddContact} from './contacts/AddContact';
export {default as EditContact} from './contacts/EditContact';
export {default as ViewContact} from './contacts/ViewContact';
export {default as Loader} from './Loader';
export {default as Contacts} from './contacts/Contacts';
export {default as Contact} from './contacts/Contact';
export {default as NavBar} from './NavBar';
export {default as App} from './App';
export {default as SearchContact} from './contacts/SearchContact';
