export {default as AddContact} from './Contacts/AddContact';
export {default as EditContact} from './Contacts/EditContact';
export {default as ViewContact} from './Contacts/ViewContact';
export {default as Loader} from './Loader';
export {default as Contacts} from './Contacts/Contacts';
export {default as Contact} from './Contacts/Contact';
export {default as NavBar} from './NavBar';
export {default as App} from './App';
export {default as SearchContact} from './Contacts/SearchContact';